{
    "0" : function() { return this.tr((({ key:"No Connection" }))); },
    "101" : function() { return this.tr((({ key:"Switching Protocols" }))); },
    "102" : function() { return this.tr((({ key:"Processing" }))); },
    "200" : function() { return this.tr((({ key:"OK" }))); },
    "201" : function() { return this.tr((({ key:"Created" }))); },
    "202" : function() { return this.tr((({ key:"Accepted" }))); },
    "203" : function() { return this.tr((({ key:"Non-Authoritative Information" }))); },
    "204" : function() { return this.tr((({ key:"No Content" }))); },
    "205" : function() { return this.tr((({ key:"Reset Content" }))); },
    "206" : function() { return this.tr((({ key:"Partial Content" }))); },
    "207" : function() { return this.tr((({ key:"Multi-Status" }))); },
    "300" : function() { return this.tr((({ key:"Multiple Choices" }))); },
    "301" : function() { return this.tr((({ key:"Moved Permanently" }))); },
    "302" : function() { return this.tr((({ key:"Found" }))); },
    "303" : function() { return this.tr((({ key:"See Other" }))); },
    "304" : function() { return this.tr((({ key:"Not Modified" }))); },
    "305" : function() { return this.tr((({ key:"Use Proxy" }))); },
    "306" : function() { return this.tr((({ key:"Switch Proxy" }))); },
    "307" : function() { return this.tr((({ key:"Temporary Redirect" }))); },
    "400" : function() { return this.tr((({ key:"Bad Request" }))); },
    "401" : function() { return this.tr((({ key:"Unauthorized" }))); },
    "402" : function() { return this.tr((({ key:"Payment Required" }))); },
    "403" : function() { return this.tr((({ key:"Forbidden" }))); },
    "404" : function() { return this.tr((({ key:"Not Found" }))); },
    "405" : function() { return this.tr((({ key:"Method Not Allowed" }))); },
    "406" : function() { return this.tr((({ key:"Not Acceptable" }))); },
    "407" : function() { return this.tr((({ key:"Proxy Authentication Required" }))); },
    "408" : function() { return this.tr((({ key:"Request Timeout" }))); },
    "409" : function() { return this.tr((({ key:"Conflict" }))); },
    "410" : function() { return this.tr((({ key:"Gone" }))); },
    "411" : function() { return this.tr((({ key:"Length Required" }))); },
    "412" : function() { return this.tr((({ key:"Precondition Failed" }))); },
    "413" : function() { return this.tr((({ key:"Request Entity Too Large" }))); },
    "414" : function() { return this.tr((({ key:"Request-URI Too Long" }))); },
    "415" : function() { return this.tr((({ key:"Unsupported Media Type" }))); },
    "416" : function() { return this.tr((({ key:"Requested Range Not Satisfiable" }))); },
    "417" : function() { return this.tr((({ key:"Expectation Failed" }))); },
    "422" : function() { return this.tr((({ key:"Unprocessable Entity" }))); },
    "423" : function() { return this.tr((({ key:"Locked" }))); },
    "424" : function() { return this.tr((({ key:"Failed Dependency" }))); },
    "425" : function() { return this.tr((({ key:"Unordered Collection" }))); },
    "426" : function() { return this.tr((({ key:"Upgrade Required" }))); },
    "449" : function() { return this.tr((({ key:"Retry With" }))); },
    "450" : function() { return this.tr((({ key:"Blocked by Windows Parental Controls" }))); },
    "500" : function() { return this.tr((({ key:"Internal Server Error" }))); },
    "501" : function() { return this.tr((({ key:"Not Implemented" }))); },
    "502" : function() { return this.tr((({ key:"Bad Gateway" }))); },
    "503" : function() { return this.tr((({ key:"Service Unavailable" }))); },
    "504" : function() { return this.tr((({ key:"Gateway Timeout" }))); },
    "505" : function() { return this.tr((({ key:"HTTP Version Not Supported" }))); },
    "506" : function() { return this.tr((({ key:"Variant Also Negotiates" }))); },
    "507" : function() { return this.tr((({ key:"Insufficient Storage" }))); },
    "509" : function() { return this.tr((({ key:"Bandwidth Limit Exceeded" }))); },
    "510" : function() { return this.tr((({ key:"Not Extended" }))); }
}
