{
    "101" : function() { return this.gettext("Switching Protocols"); },
    "102" : function() { return this.gettext("Processing"); },
    "200" : function() { return this.gettext("OK"); },
    "201" : function() { return this.gettext("Created"); },
    "202" : function() { return this.gettext("Accepted"); },
    "203" : function() { return this.gettext("Non-Authoritative Information"); },
    "204" : function() { return this.gettext("No Content"); },
    "205" : function() { return this.gettext("Reset Content"); },
    "206" : function() { return this.gettext("Partial Content"); },
    "207" : function() { return this.gettext("Multi-Status"); },
    "300" : function() { return this.gettext("Multiple Choices"); },
    "301" : function() { return this.gettext("Moved Permanently"); },
    "302" : function() { return this.gettext("Found"); },
    "303" : function() { return this.gettext("See Other"); },
    "304" : function() { return this.gettext("Not Modified"); },
    "305" : function() { return this.gettext("Use Proxy"); },
    "306" : function() { return this.gettext("Switch Proxy"); },
    "307" : function() { return this.gettext("Temporary Redirect"); },
    "400" : function() { return this.gettext("Bad Request"); },
    "401" : function() { return this.gettext("Unauthorized"); },
    "402" : function() { return this.gettext("Payment Required"); },
    "403" : function() { return this.gettext("Forbidden"); },
    "404" : function() { return this.gettext("Not Found"); },
    "405" : function() { return this.gettext("Method Not Allowed"); },
    "406" : function() { return this.gettext("Not Acceptable"); },
    "407" : function() { return this.gettext("Proxy Authentication Required"); },
    "408" : function() { return this.gettext("Request Timeout"); },
    "409" : function() { return this.gettext("Conflict"); },
    "410" : function() { return this.gettext("Gone"); },
    "411" : function() { return this.gettext("Length Required"); },
    "412" : function() { return this.gettext("Precondition Failed"); },
    "413" : function() { return this.gettext("Request Entity Too Large"); },
    "414" : function() { return this.gettext("Request-URI Too Long"); },
    "415" : function() { return this.gettext("Unsupported Media Type"); },
    "416" : function() { return this.gettext("Requested Range Not Satisfiable"); },
    "417" : function() { return this.gettext("Expectation Failed"); },
    "422" : function() { return this.gettext("Unprocessable Entity"); },
    "423" : function() { return this.gettext("Locked"); },
    "424" : function() { return this.gettext("Failed Dependency"); },
    "425" : function() { return this.gettext("Unordered Collection"); },
    "426" : function() { return this.gettext("Upgrade Required"); },
    "449" : function() { return this.gettext("Retry With"); },
    "450" : function() { return this.gettext("Blocked by Windows Parental Controls"); },
    "500" : function() { return this.gettext("Internal Server Error"); },
    "501" : function() { return this.gettext("Not Implemented"); },
    "502" : function() { return this.gettext("Bad Gateway"); },
    "503" : function() { return this.gettext("Service Unavailable"); },
    "504" : function() { return this.gettext("Gateway Timeout"); },
    "505" : function() { return this.gettext("HTTP Version Not Supported"); },
    "506" : function() { return this.gettext("Variant Also Negotiates"); },
    "507" : function() { return this.gettext("Insufficient Storage"); },
    "509" : function() { return this.gettext("Bandwidth Limit Exceeded"); },
    "510" : function() { return this.gettext("Not Extended"); }
}
